# Generated by Django 3.0.6 on 2020-09-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='miRDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirna', models.CharField(max_length=300)),
                ('geneName', models.CharField(max_length=300)),
                ('score', models.FloatField()),
                ('species', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tarbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirna', models.CharField(max_length=300)),
                ('geneName', models.CharField(max_length=300)),
                ('species', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=300)),
                ('direct_indirect', models.CharField(max_length=300)),
                ('up_down', models.CharField(max_length=300)),
            ],
        ),
    ]
