# Generated by Django 3.0.6 on 2020-09-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirna_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirna', models.CharField(max_length=500)),
                ('gene_id', models.CharField(blank=True, max_length=500, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=500, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('specie', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
